# -*- coding: utf-8 -*-
"""myfile.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11vkRJEK0CRUyRlNDwz9s_vgXMLWCgPO4
"""

name = input("Enter Your good Name: ")
print("your Name is ", name)
print("Added 2nd print statement")